# Generated by Django 5.2.17 on 2026-09-01 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_church_email_confirmed_alter_church_plano_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('preacher_name', models.CharField(blank=True, max_length=150, verbose_name='Pregador')),
                ('date', models.DateField(verbose_name='Data')),
                ('series', models.CharField(blank=True, help_text="Agrupamento livre (ex.: 'Provérbios', 'Ano Novo 2026').", max_length=150, verbose_name='Série')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('audio_file', models.FileField(blank=True, help_text='MP3/M4A — tocado direto na página pública.', upload_to='sermons/audio/%Y/%m/', verbose_name='Arquivo de áudio')),
                ('youtube_url', models.URLField(blank=True, verbose_name='Link do YouTube')),
                ('external_video_url', models.URLField(blank=True, help_text='Instagram, Facebook etc. — mostrado como botão quando não for YouTube.', verbose_name='Outro link de vídeo')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
            ],
            options={
                'verbose_name': 'Sermão',
                'verbose_name_plural': 'Sermões',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
