# Generated by Django 5.2.17 on 2026-09-03 20:38

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='audio_file',
            field=models.FileField(blank=True, help_text='MP3/M4A — tocado direto na página pública.', upload_to=core.uploads._RandomUploadTo('sermons/audio'), verbose_name='Arquivo de áudio'),
        ),
    ]
