# Generated by Django 5.2.17 on 2026-08-24 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/covers/', verbose_name='Imagem de capa')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Local')),
                ('start_datetime', models.DateTimeField(verbose_name='Início')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Término')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Evento pago')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Ignorado quando o evento é gratuito.', max_digits=8, verbose_name='Valor (R$)')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Deixe em branco para vagas ilimitadas.', null=True, verbose_name='Vagas')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicado'), ('CLOSED', 'Encerrado')], default='DRAFT', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone (WhatsApp)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('payment_status', models.CharField(choices=[('FREE', 'Gratuito'), ('PENDING', 'Aguardando pagamento'), ('PAID', 'Pago'), ('CANCELLED', 'Cancelado')], default='FREE', max_length=10, verbose_name='Status de pagamento')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor pago (R$)')),
                ('payment_reference', models.CharField(blank=True, help_text='ID da transação/PIX no gateway (Stripe/MercadoPago).', max_length=100, verbose_name='Referência de pagamento')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Inscrito em')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='Evento')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registrations', to='people.person', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-registered_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('person__isnull', False)), fields=('event', 'person'), name='unique_person_per_event')],
            },
        ),
    ]
