# Generated by Django 5.2.17 on 2026-08-27 00:41

import uuid
from django.db import migrations, models


def gerar_tokens_unicos(apps, schema_editor):
    """SQLite avalia um default `callable` em AddField uma única vez para
    todas as linhas existentes (vira um literal fixo no `INSERT ... SELECT`
    de reconstrução da tabela) — sem isso, as inscrições já existentes
    ficariam todas com o MESMO `checkin_token`, quebrando a constraint de
    unicidade adicionada logo depois. Cada linha recebe um UUID novo aqui,
    antes de `unique=True` entrar em vigor."""
    Registration = apps.get_model("events", "Registration")
    for registration in Registration.objects.all():
        registration.checkin_token = uuid.uuid4()
        registration.save(update_fields=["checkin_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='brand_color',
            field=models.CharField(blank=True, help_text='Deixe em branco para usar a cor padrão da igreja na página pública deste evento.', max_length=7, verbose_name='Cor do evento'),
        ),
        migrations.AddField(
            model_name='event',
            name='extra_info',
            field=models.TextField(blank=True, help_text='Ex.: o que levar, ponto de encontro, contato do responsável — aparece na página pública.', verbose_name='Informações adicionais'),
        ),
        migrations.AddField(
            model_name='registration',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-in em'),
        ),
        migrations.AddField(
            model_name='registration',
            name='checkin_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False),
        ),
        migrations.RunPython(gerar_tokens_unicos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='registration',
            name='checkin_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='on_waitlist',
            field=models.BooleanField(default=False, help_text='Marcado automaticamente quando o evento já estava lotado no momento da inscrição.', verbose_name='Na lista de espera'),
        ),
    ]
