# Generated by Django 5.2.17 on 2026-08-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome da igreja')),
                ('pastor_name', models.CharField(blank=True, max_length=150, verbose_name='Nome do pastor')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='core/', verbose_name='Logo')),
                ('whatsapp_absence_template', models.TextField(default='Olá {nome}, sentimos sua falta nos últimos cultos. O pastor {pastor} pediu para entrar em contato e saber como você está.', help_text='Use {nome} e {pastor} como marcadores.', verbose_name='Modelo de mensagem — ausência')),
            ],
            options={
                'verbose_name': 'Configuração da igreja',
                'verbose_name_plural': 'Configuração da igreja',
            },
        ),
    ]
