# Generated by Django 5.2.17 on 2026-08-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchconfig',
            name='pix_key',
            field=models.CharField(blank=True, help_text='Usada para gerar o QR Code de pagamento de eventos pagos.', max_length=140, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='churchconfig',
            name='pix_key_type',
            field=models.CharField(blank=True, choices=[('CPF_CNPJ', 'CPF/CNPJ'), ('EMAIL', 'E-mail'), ('PHONE', 'Telefone'), ('RANDOM', 'Chave aleatória')], max_length=10, verbose_name='Tipo da chave PIX'),
        ),
        migrations.AddField(
            model_name='churchconfig',
            name='pix_receiver_city',
            field=models.CharField(blank=True, help_text='Máx. 15 caracteres — exigido pelo padrão do Banco Central.', max_length=15, verbose_name='Cidade do recebedor (PIX)'),
        ),
        migrations.AddField(
            model_name='churchconfig',
            name='pix_receiver_name',
            field=models.CharField(blank=True, help_text='Máx. 25 caracteres — exigido pelo padrão do Banco Central.', max_length=25, verbose_name='Nome do recebedor (PIX)'),
        ),
    ]
