# Generated by Django 5.2.17 on 2026-08-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_churchconfig_pix_key_churchconfig_pix_key_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchconfig',
            name='brand_color',
            field=models.CharField(default='#2563eb', help_text='Usada para gerar a paleta de cores do sistema (botões, links etc.).', max_length=7, verbose_name='Cor de marca'),
        ),
        migrations.AddField(
            model_name='churchconfig',
            name='mercadopago_access_token',
            field=models.CharField(blank=True, help_text='Gerado no painel de desenvolvedor do Mercado Pago — habilita checkout com confirmação automática.', max_length=200, verbose_name='Access Token do Mercado Pago'),
        ),
    ]
