# Generated by Django 5.2.17 on 2026-08-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_churchconfig_brand_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchconfig',
            name='whatsapp_api_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='Chave da API de WhatsApp'),
        ),
        migrations.AddField(
            model_name='churchconfig',
            name='whatsapp_api_url',
            field=models.URLField(blank=True, verbose_name='URL da API de WhatsApp'),
        ),
        migrations.AddField(
            model_name='churchconfig',
            name='whatsapp_birthday_template',
            field=models.TextField(default='Feliz aniversário, {nome}! 🎉 Que Deus continue te abençoando. Um abraço, {pastor}.', help_text='Use {nome} e {pastor} como marcadores.', verbose_name='Modelo de mensagem — aniversário'),
        ),
        migrations.AddField(
            model_name='churchconfig',
            name='whatsapp_instance',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instância'),
        ),
    ]
