# Generated by Django 5.2.17 on 2026-08-24 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_churchconfig_whatsapp_api_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Edição'), ('DELETE', 'Exclusão')], max_length=10, verbose_name='Ação')),
                ('model_name', models.CharField(max_length=50, verbose_name='Model')),
                ('object_repr', models.CharField(max_length=255, verbose_name='Registro')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='ID do registro')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Quando')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de auditoria',
                'verbose_name_plural': 'Logs de auditoria',
                'ordering': ['-timestamp'],
            },
        ),
    ]
