# Generated by Django 5.2.17 on 2026-08-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchconfig',
            name='whatsapp_batch_size',
            field=models.PositiveIntegerField(default=30, help_text='Limite de mensagens enviadas em uma única chamada do comando processar_fila_whatsapp — o resto fica pra próxima execução do cron.', verbose_name='Mensagens por execução da fila'),
        ),
        migrations.AddField(
            model_name='churchconfig',
            name='whatsapp_instance_token',
            field=models.CharField(blank=True, help_text='Preenchida automaticamente ao criar a instância pelo admin. Se vazio, usa a chave global acima.', max_length=200, verbose_name='Chave da instância'),
        ),
        migrations.AddField(
            model_name='churchconfig',
            name='whatsapp_send_interval_seconds',
            field=models.PositiveIntegerField(default=6, help_text='Espera entre uma mensagem e outra ao processar a fila — mandar tudo de uma vez é o jeito mais rápido do WhatsApp marcar o número como spam. 5-10s é um valor seguro.', verbose_name='Intervalo entre envios (segundos)'),
        ),
        migrations.AlterField(
            model_name='churchconfig',
            name='whatsapp_api_key',
            field=models.CharField(blank=True, help_text='A AUTHENTICATION_API_KEY do servidor — usada para criar/gerenciar instâncias.', max_length=200, verbose_name='Chave global (admin) da Evolution API'),
        ),
        migrations.AlterField(
            model_name='churchconfig',
            name='whatsapp_api_url',
            field=models.URLField(blank=True, help_text='Ex.: https://evolution.suaigreja.com (sem barra no final).', verbose_name='URL da instância Evolution API'),
        ),
        migrations.AlterField(
            model_name='churchconfig',
            name='whatsapp_instance',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome da instância'),
        ),
    ]
