# Generated by Django 5.2.17 on 2026-08-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_churchconfig_whatsapp_batch_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchconfig',
            name='whatsapp_max_retries',
            field=models.PositiveIntegerField(default=3, help_text='Quantas vezes o processador da fila tenta reenviar uma mensagem que falhou antes de parar de tentar sozinho (ainda dá pra reenviar manualmente depois).', verbose_name='Tentativas antes de desistir'),
        ),
        migrations.AddField(
            model_name='churchconfig',
            name='whatsapp_webhook_secret',
            field=models.CharField(blank=True, help_text='A Evolution API não assina os webhooks — esse valor é conferido no cabeçalho X-Webhook-Secret pra confirmar que a chamada é legítima. Configure o mesmo valor no painel da sua instância Evolution.', max_length=100, verbose_name='Segredo do webhook'),
        ),
    ]
