# Generated by Django 5.2.17 on 2026-08-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_churchconfig_whatsapp_max_retries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchconfig',
            name='admin_alert_emails',
            field=models.CharField(blank=True, help_text='Um ou mais e-mails separados por vírgula — avisados se o WhatsApp desconectar sozinho, por exemplo. Deixe em branco pra não avisar ninguém.', max_length=500, verbose_name='E-mails de alerta administrativo'),
        ),
        migrations.AddField(
            model_name='churchconfig',
            name='whatsapp_disconnect_alert_sent',
            field=models.BooleanField(default=False, help_text='Controle interno de `verificar_conexao_whatsapp` — evita mandar um e-mail novo a cada execução do cron enquanto a mesma queda continua; zera sozinho quando reconectar.', verbose_name='Já avisou sobre desconexão atual'),
        ),
    ]
