# Generated by Django 5.2.17 on 2026-08-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auditlog_church'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='whatsapp_instance_token',
            field=models.CharField(blank=True, help_text='Preenchida automaticamente ao criar a instância pelo admin.', max_length=200, verbose_name='Chave da instância'),
        ),
    ]
