# Generated by Django 5.2.17 on 2026-08-31 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_church_whatsapp_instance_token'),
        ('people', '0004_person_privacy_consent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='email_confirmed',
            field=models.BooleanField(default=False, help_text='Confirmado pelo link enviado no cadastro público (core.ChurchSignupView). Enquanto falso, o envio de WhatsApp desta igreja fica bloqueado — não afeta o resto do sistema, que já pode ser usado normalmente durante o trial.', verbose_name='E-mail confirmado'),
        ),
        migrations.AlterField(
            model_name='church',
            name='plano',
            field=models.CharField(blank=True, choices=[('basico', 'Básico'), ('pro', 'Pro')], max_length=20, verbose_name='Plano'),
        ),
        migrations.CreateModel(
            name='DataDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200, verbose_name='Nome da pessoa')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Solicitado em')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('DONE', 'Concluído')], default='PENDING', max_length=10, verbose_name='Status')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests', to='people.person', verbose_name='Pessoa')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Processado por')),
            ],
            options={
                'verbose_name': 'Solicitação de exclusão de dados',
                'verbose_name_plural': 'Solicitações de exclusão de dados',
                'ordering': ['-requested_at'],
            },
        ),
    ]
