# Generated by Django 5.2.17 on 2026-09-02 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_church_email_confirmed_alter_church_plano_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='A parte depois de igrejago.link/ — só letras, números e hífen.', max_length=60, unique=True, verbose_name='Link personalizado')),
                ('label', models.CharField(help_text='Só pra você reconhecer na lista (ex.: "Link da Bio", "Inscrição Batismo").', max_length=150, verbose_name='Identificação')),
                ('target_path', models.CharField(help_text='Caminho ou link completo pra onde esse link curto deve levar.', max_length=300, verbose_name='Destino')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('click_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Cliques')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
            ],
            options={
                'verbose_name': 'Link curto',
                'verbose_name_plural': 'Links curtos',
                'ordering': ['-created_at'],
            },
        ),
    ]
