# Generated by Django 5.2.17 on 2026-09-02 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_shortlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='api_key',
            field=models.CharField(blank=True, help_text='Gerada em Configurações — usada por integrações externas (API de leitura) via cabeçalho Authorization: Bearer <chave>.', max_length=64, null=True, unique=True, verbose_name='Chave da API'),
        ),
        migrations.AddField(
            model_name='church',
            name='email_batch_size',
            field=models.PositiveIntegerField(default=50, help_text='Quantos e-mails de campanha a fila manda por vez — evita estourar a cota do provedor SMTP.', verbose_name='Lote de e-mail por execução'),
        ),
        migrations.AddField(
            model_name='church',
            name='matriz',
            field=models.ForeignKey(blank=True, help_text='Em branco = é uma matriz (ou igreja independente). Preenchido = é filial dessa igreja — compartilha o seletor de unidade no menu, mas `status`/`plano` continuam por conta própria (sem cobrança automática por filial; ajuste manual pelo dono da plataforma se for o caso).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filiais', to='core.church', verbose_name='Igreja-mãe'),
        ),
    ]
