# Generated by Django 5.2.17 on 2026-09-02 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_church_api_key_church_email_batch_size_church_matriz'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL de destino')),
                ('event_type', models.CharField(choices=[('PERSON_CREATED', 'Nova pessoa cadastrada'), ('DONATION_RECEIVED', 'Doação recebida'), ('EVENT_REGISTRATION_CREATED', 'Nova inscrição em evento')], max_length=30, verbose_name='Evento')),
                ('secret', models.CharField(editable=False, max_length=64, verbose_name='Segredo (HMAC)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
            ],
            options={
                'verbose_name': 'Assinatura de webhook',
                'verbose_name_plural': 'Assinaturas de webhook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PERSON_CREATED', 'Nova pessoa cadastrada'), ('DONATION_RECEIVED', 'Doação recebida'), ('EVENT_REGISTRATION_CREATED', 'Nova inscrição em evento')], max_length=30, verbose_name='Evento')),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando'), ('SENT', 'Entregue'), ('FAILED', 'Falhou')], default='PENDING', max_length=10, verbose_name='Status')),
                ('response_status_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='Status HTTP da resposta')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='Tentativas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.webhooksubscription', verbose_name='Assinatura')),
            ],
            options={
                'verbose_name': 'Entrega de webhook',
                'verbose_name_plural': 'Entregas de webhook',
                'ordering': ['-created_at'],
            },
        ),
    ]
