# Generated by Django 5.2.17 on 2026-09-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_webhooksubscription_webhookdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='whatsapp_escala_template',
            field=models.TextField(default='Olá {nome}! Você foi escalado(a) para {departamento}{funcao} — {data}{horario}. Confirma presença? {link}', help_text='Use {nome}, {departamento}, {data}, {horario}, {funcao} e {link} como marcadores — {horario} e {funcao} já vêm formatados (" às 19:00", " como Vocal") ou em branco quando não se aplicam, sem precisar tratar isso no texto.', verbose_name='Modelo de mensagem — escala'),
        ),
        migrations.AddField(
            model_name='church',
            name='whatsapp_meta_access_token',
            field=models.CharField(blank=True, help_text='Token permanente gerado no painel de desenvolvedor da Meta pra essa aplicação.', max_length=500, verbose_name='Access Token (Meta Cloud API)'),
        ),
        migrations.AddField(
            model_name='church',
            name='whatsapp_meta_phone_number_id',
            field=models.CharField(blank=True, help_text='Do painel de desenvolvedor da Meta (developers.facebook.com) — infraestrutura da própria igreja, não desta plataforma.', max_length=100, verbose_name='Phone Number ID (Meta Cloud API)'),
        ),
        migrations.AddField(
            model_name='church',
            name='whatsapp_provider',
            field=models.CharField(choices=[('EVOLUTION', 'Evolution API'), ('META_CLOUD', 'API oficial da Meta (WhatsApp Cloud API)')], default='EVOLUTION', help_text='Evolution API (padrão, QR code) ou a API oficial da Meta — configurável na tela de Conectar WhatsApp. Trocar aqui não apaga a configuração do outro canal.', max_length=20, verbose_name='Canal de WhatsApp'),
        ),
    ]
