# Generated by Django 5.2.17 on 2026-09-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_church_whatsapp_escala_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='whatsapp_meta_business_account_id',
            field=models.CharField(blank=True, help_text='Do painel de desenvolvedor da Meta — necessário só pra gerenciar templates de mensagem (criar/enviar pra aprovação), não pra mandar mensagem avulsa.', max_length=100, verbose_name='WhatsApp Business Account ID (Meta Cloud API)'),
        ),
    ]
