# Generated by Django 5.2.17 on 2026-09-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_church_whatsapp_meta_business_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='android_package_name',
            field=models.CharField(blank=True, help_text='Preenchido só se/quando essa igreja publicar o próprio app na Play Store (via TWA — ver DEPLOY.md). Sem isso, o app instalado continua funcionando normalmente (PWA).', max_length=150, verbose_name='Nome do pacote Android'),
        ),
        migrations.AddField(
            model_name='church',
            name='android_sha256_fingerprint',
            field=models.CharField(blank=True, help_text='Gerado ao assinar o app Android — necessário junto com o nome do pacote acima pra validar o app na Play Store (Digital Asset Links).', max_length=100, verbose_name='Fingerprint SHA256 do certificado Android'),
        ),
        migrations.AddField(
            model_name='church',
            name='pagbank_token',
            field=models.CharField(blank=True, help_text='Gerado no painel de desenvolvedor do PagBank (developer.pagbank.com.br) — segundo gateway de pagamento, independente do Mercado Pago (dá pra ter os dois configurados ao mesmo tempo).', max_length=200, verbose_name='Token do PagBank'),
        ),
        migrations.AlterField(
            model_name='church',
            name='whatsapp_meta_phone_number_id',
            field=models.CharField(blank=True, db_index=True, help_text='Do painel de desenvolvedor da Meta (developers.facebook.com) — infraestrutura da própria igreja, não desta plataforma. Indexado: é por esse valor que o webhook oficial da Meta descobre de qual igreja é um evento de entrega de mensagem.', max_length=100, verbose_name='Phone Number ID (Meta Cloud API)'),
        ),
    ]
