# Generated by Django 5.2.17 on 2026-09-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_church_android_package_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='whatsapp_max_instancias',
            field=models.PositiveIntegerField(default=1, help_text='Quantas instâncias Evolution API essa igreja pode conectar ao mesmo tempo — ajuste manual, sem regra fixa de plano ainda.', verbose_name='Limite de números de WhatsApp (Evolution)'),
        ),
        migrations.AlterField(
            model_name='church',
            name='whatsapp_batch_size',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='church',
            name='whatsapp_instance',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome da instância (legado)'),
        ),
        migrations.AlterField(
            model_name='church',
            name='whatsapp_instance_token',
            field=models.CharField(blank=True, max_length=200, verbose_name='Chave da instância (legado)'),
        ),
        migrations.AlterField(
            model_name='church',
            name='whatsapp_max_retries',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='church',
            name='whatsapp_send_interval_seconds',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='church',
            name='whatsapp_webhook_secret',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
