# Generated by Django 5.2.17 on 2026-09-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_church_whatsapp_max_instancias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='whatsapp_instance',
        ),
        migrations.RemoveField(
            model_name='church',
            name='whatsapp_instance_token',
        ),
        migrations.RemoveField(
            model_name='church',
            name='whatsapp_webhook_secret',
        ),
        migrations.AlterField(
            model_name='church',
            name='whatsapp_batch_size',
            field=models.PositiveIntegerField(default=30, help_text='Só vale pro canal oficial da Meta — mesmo motivo do campo acima.', verbose_name='Mensagens por execução da fila — Meta Cloud'),
        ),
        migrations.AlterField(
            model_name='church',
            name='whatsapp_max_retries',
            field=models.PositiveIntegerField(default=3, help_text='Só vale pro canal oficial da Meta — mesmo motivo do campo acima.', verbose_name='Tentativas antes de desistir — Meta Cloud'),
        ),
        migrations.AlterField(
            model_name='church',
            name='whatsapp_send_interval_seconds',
            field=models.PositiveIntegerField(default=6, help_text='Só vale pro canal oficial da Meta — no Evolution, cada número conectado tem o próprio intervalo (editável na tela de Conectar WhatsApp).', verbose_name='Intervalo entre envios — Meta Cloud (segundos)'),
        ),
    ]
