# Generated by Django 5.2.17 on 2026-09-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_church_whatsapp_instance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='whatsapp_disconnect_alert_sent',
        ),
    ]
