# Generated by Django 5.2.17 on 2026-09-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_church_whatsapp_disconnect_alert_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='ia_api_key',
            field=models.CharField(blank=True, help_text='Gerada no painel do provedor escolhido acima (Google AI Studio ou platform.openai.com) — cada igreja usa a própria chave, mesmo espírito do Mercado Pago/PagBank.', max_length=200, verbose_name='Chave da API de IA'),
        ),
        migrations.AddField(
            model_name='church',
            name='ia_chat_enabled',
            field=models.BooleanField(default=False, help_text='Liga/desliga o atendimento automático sem apagar a chave/base de conhecimento salvas.', verbose_name='Assistente de WhatsApp ativo'),
        ),
        migrations.AddField(
            model_name='church',
            name='ia_knowledge_base',
            field=models.TextField(blank=True, help_text='Texto livre (horários de culto, endereço, ministérios, perguntas frequentes...) que o assistente usa como contexto pra responder no WhatsApp.', verbose_name='Base de conhecimento do assistente'),
        ),
        migrations.AddField(
            model_name='church',
            name='ia_provider',
            field=models.CharField(blank=True, choices=[('GEMINI', 'Google Gemini'), ('CHATGPT', 'ChatGPT (OpenAI)')], help_text='Quem responde no assistente de WhatsApp (menu opção 3) — Google Gemini ou ChatGPT (OpenAI).', max_length=10, verbose_name='Provedor de IA'),
        ),
    ]
