# Generated by Django 5.2.17 on 2026-09-03 20:38

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_church_ia_api_key_church_ia_chat_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.uploads._RandomUploadTo('core'), verbose_name='Logo'),
        ),
    ]
