# Generated by Django 5.2.17 on 2026-08-24 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INCOME', 'Entrada'), ('EXPENSE', 'Saída')], max_length=10, verbose_name='Tipo')),
                ('category', models.CharField(choices=[('TITHE', 'Dízimo'), ('OFFERING', 'Oferta'), ('DONATION', 'Doação'), ('EVENT', 'Evento'), ('OTHER_INCOME', 'Outra entrada'), ('SALARY', 'Salário / pró-labore'), ('MAINTENANCE', 'Manutenção'), ('UTILITIES', 'Água / luz / internet'), ('MATERIALS', 'Materiais'), ('RENT', 'Aluguel'), ('OTHER_EXPENSE', 'Outra saída')], max_length=20, verbose_name='Categoria')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('date', models.DateField(verbose_name='Data')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Dinheiro'), ('PIX', 'PIX'), ('TRANSFER', 'Transferência'), ('CARD', 'Cartão'), ('OTHER', 'Outro')], max_length=10, verbose_name='Forma de pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Lançado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_created', to=settings.AUTH_USER_MODEL, verbose_name='Lançado por')),
                ('person', models.ForeignKey(blank=True, help_text='Opcional — quem deu o dízimo/oferta, para histórico individual.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='people.person', verbose_name='Contribuinte')),
            ],
            options={
                'verbose_name': 'Lançamento',
                'verbose_name_plural': 'Lançamentos',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
