# Generated by Django 5.2.17 on 2026-08-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TITHE', 'Dízimo'), ('OFFERING', 'Oferta'), ('DONATION', 'Doação'), ('EVENT', 'Evento'), ('OTHER_INCOME', 'Outra entrada'), ('SALARY', 'Salário / pró-labore'), ('MAINTENANCE', 'Manutenção'), ('UTILITIES', 'Água / luz / internet'), ('MATERIALS', 'Materiais'), ('RENT', 'Aluguel'), ('OTHER_EXPENSE', 'Outra saída')], max_length=20, verbose_name='Categoria')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Mês')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor previsto (R$)')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-year', '-month', 'category'],
                'constraints': [models.UniqueConstraint(fields=('category', 'year', 'month'), name='unique_budget_per_month')],
            },
        ),
    ]
