# Generated by Django 5.2.17 on 2026-08-27 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_budget'),
        ('people', '0002_family_tag_person_pipeline_stage_person_family_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando confirmação'), ('PAID', 'Confirmada')], default='PENDING', max_length=10, verbose_name='Status')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Referência de pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='people.person', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor mensal (R$)')),
                ('due_day', models.PositiveSmallIntegerField(default=10, help_text='Dia do mês (1 a 28).', verbose_name='Dia de vencimento')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_pledges', to='people.person', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Contribuição recorrente',
                'verbose_name_plural': 'Contribuições recorrentes',
                'ordering': ['person__full_name'],
            },
        ),
    ]
