# Generated by Django 5.2.17 on 2026-09-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_church_scoping'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringpledge',
            name='mercadopago_preapproval_id',
            field=models.CharField(blank=True, help_text='Preenchido só quando o membro assinou pelo Portal — em branco = compromisso manual.', max_length=100, verbose_name='ID da assinatura no Mercado Pago'),
        ),
        migrations.AddField(
            model_name='recurringpledge',
            name='mercadopago_status',
            field=models.CharField(blank=True, help_text='Espelha o status real da API (authorized/paused/cancelled) — nunca decidido localmente.', max_length=30, verbose_name='Status da assinatura no Mercado Pago'),
        ),
    ]
