# Generated by Django 5.2.17 on 2026-09-02 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_webhooksubscription_webhookdelivery'),
        ('finance', '0005_recurringpledge_mercadopago_preapproval_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Livre — numere do jeito que seu contador pedir (ex.: 3.1.01).', max_length=20, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nome da conta')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa'), ('ATIVO', 'Ativo'), ('PASSIVO', 'Passivo'), ('PATRIMONIO_LIQUIDO', 'Patrimônio líquido')], max_length=20, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.contacontabil', verbose_name='Conta superior')),
            ],
            options={
                'verbose_name': 'Conta contábil',
                'verbose_name_plural': 'Plano de contas',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='conta_contabil',
            field=models.ForeignKey(blank=True, help_text='Opcional — só pra quem já montou um plano de contas (Financeiro → Plano de contas).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.contacontabil', verbose_name='Conta contábil'),
        ),
    ]
