# Generated by Django 5.2.17 on 2026-09-02 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_contacontabil_transaction_conta_contabil'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacontabil',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quanto essa conta já tinha antes de você começar a registrar por aqui — só relevante pra contas de Ativo/Passivo/Patrimônio líquido (ex.: saldo do caixa/banco).', max_digits=12, verbose_name='Saldo de abertura (R$)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='conta_contrapartida',
            field=models.ForeignKey(blank=True, help_text='O outro lado do lançamento (ex.: de onde saiu/pra onde foi o dinheiro — Caixa, Banco) — preenchendo as duas contas, o lançamento vira partida dobrada de verdade (ver Financeiro → Balanço patrimonial).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_contrapartida', to='finance.contacontabil', verbose_name='Conta de contrapartida'),
        ),
    ]
