# Generated by Django 5.2.17 on 2026-09-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_contacontabil_saldo_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacontabil',
            name='saldo_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Quanto essa conta já tinha antes de você começar a registrar por aqui — só relevante pra contas de Ativo/Passivo/Patrimônio líquido (ex.: saldo do caixa/banco).', max_digits=12, verbose_name='Saldo de abertura (R$)'),
        ),
    ]
