from django.urls import path

from people.views import (
    CampaignSendView,
    DepartmentCreateView,
    DepartmentDeleteView,
    DepartmentListView,
    DepartmentUpdateView,
    EmailCampaignSendView,
    FamilyDeleteView,
    FamilyDetailView,
    FamilyListView,
    PersonCreateAccessView,
    PersonCreateView,
    PersonDeleteView,
    PersonDetailView,
    PersonImportTemplateView,
    PersonImportView,
    PersonListView,
    PersonUpdateRoleView,
    PersonUpdateView,
    PipelineBoardView,
    PipelineMoveView,
    SMSCampaignSendView,
    TagDeleteView,
    TagListView,
)

app_name = "people"

urlpatterns = [
    path("", PersonListView.as_view(), name="list"),
    path("novo/", PersonCreateView.as_view(), name="create"),
    path("campanha/", CampaignSendView.as_view(), name="campaign"),
    path("campanha/email/", EmailCampaignSendView.as_view(), name="email_campaign"),
    path("campanha/sms/", SMSCampaignSendView.as_view(), name="sms_campaign"),
    path("importar/", PersonImportView.as_view(), name="import"),
    path("importar/modelo/", PersonImportTemplateView.as_view(), name="import_template"),
    path("acompanhamento/", PipelineBoardView.as_view(), name="pipeline_board"),
    path("acompanhamento/<int:pk>/mover/", PipelineMoveView.as_view(), name="pipeline_move"),
    path("familias/", FamilyListView.as_view(), name="family_list"),
    path("familias/<int:pk>/", FamilyDetailView.as_view(), name="family_detail"),
    path("familias/<int:pk>/excluir/", FamilyDeleteView.as_view(), name="family_delete"),
    path("tags/", TagListView.as_view(), name="tag_list"),
    path("tags/<int:pk>/excluir/", TagDeleteView.as_view(), name="tag_delete"),
    path("departamentos/", DepartmentListView.as_view(), name="department_list"),
    path("departamentos/novo/", DepartmentCreateView.as_view(), name="department_create"),
    path("departamentos/<int:pk>/editar/", DepartmentUpdateView.as_view(), name="department_update"),
    path("departamentos/<int:pk>/excluir/", DepartmentDeleteView.as_view(), name="department_delete"),
    path("<int:pk>/", PersonDetailView.as_view(), name="detail"),
    path("<int:pk>/editar/", PersonUpdateView.as_view(), name="update"),
    path("<int:pk>/excluir/", PersonDeleteView.as_view(), name="delete"),
    path("<int:pk>/criar-acesso/", PersonCreateAccessView.as_view(), name="create_access"),
    path("<int:pk>/atualizar-acesso/", PersonUpdateRoleView.as_view(), name="update_role"),
]
