# Generated by Django 5.2.17 on 2026-09-01 21:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_church_email_confirmed_alter_church_plano_and_more'),
        ('people', '0005_person_guardian_person_medical_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Horário')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='people.department', verbose_name='Ministério')),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='EscalaVoluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando confirmação'), ('CONFIRMED', 'Confirmado'), ('DECLINED', 'Não vai poder ir')], default='PENDING', max_length=10, verbose_name='Status')),
                ('confirm_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido em')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voluntarios', to='escalas.escala', verbose_name='Escala')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas_voluntario', to='people.person', verbose_name='Voluntário')),
            ],
            options={
                'verbose_name': 'Voluntário escalado',
                'verbose_name_plural': 'Voluntários escalados',
                'ordering': ['escala__date'],
                'constraints': [models.UniqueConstraint(fields=('escala', 'person'), name='unique_person_per_escala')],
            },
        ),
    ]
