# Generated by Django 5.2.17 on 2026-09-02 02:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_church_email_confirmed_alter_church_plano_and_more'),
        ('escalas', '0001_initial'),
        ('people', '0006_department_habilita_checkin_alter_department_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrocaEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando alguém aceitar'), ('ACEITA', 'Aceita'), ('CANCELADA', 'Cancelada')], default='PENDING', max_length=10, verbose_name='Status')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvida em')),
                ('aceito_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trocas_aceitas', to='people.person', verbose_name='Aceita por')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
                ('escala_voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas', to='escalas.escalavoluntario', verbose_name='Escalado')),
            ],
            options={
                'verbose_name': 'Troca de escala',
                'verbose_name_plural': 'Trocas de escala',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndisponibilidadeVoluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilidades', to='people.person', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Indisponibilidade',
                'verbose_name_plural': 'Indisponibilidades',
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('person', 'date'), name='unique_indisponibilidade_por_dia')],
            },
        ),
    ]
