# Generated by Django 5.2.17 on 2026-09-02 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_shortlink'),
        ('escalas', '0002_trocaescala_indisponibilidadevoluntario'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalavoluntario',
            name='role',
            field=models.CharField(blank=True, help_text='Opcional — ex.: Vocal, Baixo, Bateria, Teclado, Recepção.', max_length=100, verbose_name='Função nesse culto'),
        ),
        migrations.CreateModel(
            name='ServiceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('title', models.CharField(max_length=150, verbose_name='Item')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (min)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observações')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_culto', to='escalas.escala', verbose_name='Escala')),
            ],
            options={
                'verbose_name': 'Item da ordem do culto',
                'verbose_name_plural': 'Itens da ordem do culto',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('artist', models.CharField(blank=True, max_length=150, verbose_name='Artista/banda')),
                ('default_key', models.CharField(blank=True, max_length=10, verbose_name='Tom padrão')),
                ('chord_chart', models.FileField(blank=True, null=True, upload_to='songs/cifras/%Y/%m/', verbose_name='Cifra (PDF ou imagem)')),
                ('lyrics', models.TextField(blank=True, verbose_name='Letra/cifra em texto')),
                ('tags', models.CharField(blank=True, help_text='Separadas por vírgula.', max_length=200, verbose_name='Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
            ],
            options={
                'verbose_name': 'Música',
                'verbose_name_plural': 'Músicas',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='EscalaSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=10, verbose_name='Tom nesse culto')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='escalas.escala', verbose_name='Escala')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='escalas.song', verbose_name='Música')),
            ],
            options={
                'verbose_name': 'Música escalada',
                'verbose_name_plural': 'Músicas escaladas',
                'ordering': ['order', 'id'],
            },
        ),
    ]
