# Generated by Django 5.2.17 on 2026-09-03 20:38

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0003_escalavoluntario_role_serviceorderitem_song_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='chord_chart',
            field=models.FileField(blank=True, null=True, upload_to=core.uploads._RandomUploadTo('songs/cifras'), verbose_name='Cifra (PDF ou imagem)'),
        ),
    ]
