from django.urls import path

from core.views import (
    AssinaturaCheckoutView,
    AssinaturaView,
    AssinaturaWebhookView,
    AuditLogListView,
    ChurchNetworkCreateView,
    ChurchNetworkDashboardView,
    ChurchNetworkListView,
    ChurchSignupDoneView,
    ChurchSignupView,
    ConfirmEmailView,
    ContaSuspensaView,
    DashboardView,
    DataDeletionRequestListView,
    DataDeletionRequestProcessView,
    GenerateApiKeyView,
    GeneralReportPDFView,
    GestaoChurchDeleteView,
    GestaoChurchDetailView,
    GestaoChurchListView,
    GestaoCommandRunView,
    GestaoCommandsView,
    GestaoDashboardView,
    ManualView,
    MeusDadosExportView,
    MeusDadosView,
    PrivacyPolicyView,
    SettingsView,
    ShortLinkCreateView,
    ShortLinkDeleteView,
    ShortLinkListView,
    ShortLinkUpdateView,
    SolicitarExclusaoView,
    SwitchChurchView,
    WebhookSubscriptionCreateView,
    WebhookSubscriptionDeleteView,
    WebhookSubscriptionListView,
    health_check,
    manifest_json,
    service_worker_js,
    short_link_redirect,
)

app_name = "core"

urlpatterns = [
    path("health/", health_check, name="health_check"),
    path("manifest.json", manifest_json, name="manifest"),
    path("sw.js", service_worker_js, name="service_worker"),
    path("relatorio.pdf", GeneralReportPDFView.as_view(), name="report_pdf"),
    path("configuracoes/", SettingsView.as_view(), name="settings"),
    path("manual/", ManualView.as_view(), name="manual"),
    path("auditoria/", AuditLogListView.as_view(), name="audit_log"),
    path("cadastro-igreja/", ChurchSignupView.as_view(), name="church_signup"),
    path("cadastro-igreja/obrigado/", ChurchSignupDoneView.as_view(), name="church_signup_done"),
    path("cadastro-igreja/confirmar/<str:token>/", ConfirmEmailView.as_view(), name="confirm_email"),
    path("conta-suspensa/", ContaSuspensaView.as_view(), name="conta_suspensa"),
    path("privacidade/", PrivacyPolicyView.as_view(), name="privacy_policy"),
    path("meus-dados/", MeusDadosView.as_view(), name="meus_dados"),
    path("meus-dados/baixar/", MeusDadosExportView.as_view(), name="meus_dados_export"),
    path("meus-dados/solicitar-exclusao/", SolicitarExclusaoView.as_view(), name="solicitar_exclusao"),
    path("privacidade/solicitacoes/", DataDeletionRequestListView.as_view(), name="data_deletion_requests"),
    path(
        "privacidade/solicitacoes/<int:pk>/confirmar/",
        DataDeletionRequestProcessView.as_view(),
        name="data_deletion_request_process",
    ),
    path("assinatura/", AssinaturaView.as_view(), name="assinatura"),
    path("assinatura/assinar/<str:plano_key>/", AssinaturaCheckoutView.as_view(), name="assinatura_checkout"),
    path("assinatura/webhook/mercadopago/", AssinaturaWebhookView.as_view(), name="assinatura_webhook"),
    path("gestao/", GestaoDashboardView.as_view(), name="gestao_dashboard"),
    path("gestao/igrejas/", GestaoChurchListView.as_view(), name="gestao_church_list"),
    path("gestao/igrejas/<int:pk>/", GestaoChurchDetailView.as_view(), name="gestao_church_detail"),
    path("gestao/igrejas/<int:pk>/excluir/", GestaoChurchDeleteView.as_view(), name="gestao_church_delete"),
    path("gestao/comandos/", GestaoCommandsView.as_view(), name="gestao_commands"),
    path(
        "gestao/comandos/<str:command_name>/executar/",
        GestaoCommandRunView.as_view(),
        name="gestao_command_run",
    ),
    path("trocar-unidade/", SwitchChurchView.as_view(), name="switch_church"),
    path("rede/", ChurchNetworkListView.as_view(), name="church_network_list"),
    path("rede/nova/", ChurchNetworkCreateView.as_view(), name="church_network_create"),
    path("rede/consolidado/", ChurchNetworkDashboardView.as_view(), name="church_network_dashboard"),
    path("webhooks/", WebhookSubscriptionListView.as_view(), name="webhook_list"),
    path("webhooks/novo/", WebhookSubscriptionCreateView.as_view(), name="webhook_create"),
    path("webhooks/<int:pk>/excluir/", WebhookSubscriptionDeleteView.as_view(), name="webhook_delete"),
    path("api-key/gerar/", GenerateApiKeyView.as_view(), name="api_key_generate"),
    path("links-curtos/", ShortLinkListView.as_view(), name="shortlink_list"),
    path("links-curtos/novo/", ShortLinkCreateView.as_view(), name="shortlink_create"),
    path("links-curtos/<int:pk>/editar/", ShortLinkUpdateView.as_view(), name="shortlink_update"),
    path("links-curtos/<int:pk>/excluir/", ShortLinkDeleteView.as_view(), name="shortlink_delete"),
    path("", DashboardView.as_view(), name="dashboard"),

    # Catch-all do link curto (`igrejago.link/<slug>`) — TEM que ser a
    # ÚLTIMA rota da lista: só entra em jogo quando nenhuma rota real do
    # sistema bateu antes (Django tenta as rotas nesta ordem, de cima pra
    # baixo). Qualquer rota nova adicionada ACIMA continua funcionando
    # normal; uma adicionada por engano ABAIXO desta linha nunca seria
    # alcançada.
    path("<slug:slug>/", short_link_redirect, name="short_link_redirect"),
]
