from django.urls import path

from finance.views import (
    AnnualDonationReceiptPDFView,
    BalanceteView,
    BudgetView,
    ContabilExportView,
    ContaContabilCreateView,
    ContaContabilDeleteView,
    ContaContabilListView,
    ContaContabilUpdateView,
    DREContabilView,
    DREView,
    DonationConfirmPixView,
    DonationCreateView,
    DonationListView,
    DonationMercadoPagoStartView,
    DonationPayView,
    DonationReceiptPDFView,
    DonationWebhookView,
    RecurringPledgeCancelView,
    RecurringPledgeDeleteView,
    RecurringPledgeListView,
    RecurringPledgeMercadoPagoWebhookView,
    RecurringPledgeSubscribeView,
    RecurringPledgeToggleView,
    TransactionCreateView,
    TransactionDeleteView,
    TransactionExportExcelView,
    TransactionExportView,
    TransactionListView,
    TransactionUpdateView,
)

app_name = "finance"

urlpatterns = [
    path("", TransactionListView.as_view(), name="list"),
    path("exportar/", TransactionExportView.as_view(), name="export"),
    path("exportar/excel/", TransactionExportExcelView.as_view(), name="export_excel"),
    path("orcamento/", BudgetView.as_view(), name="budget"),
    path("dre/", DREView.as_view(), name="dre"),
    path("balancete/", BalanceteView.as_view(), name="balancete"),
    path("plano-de-contas/", ContaContabilListView.as_view(), name="conta_contabil_list"),
    path("plano-de-contas/novo/", ContaContabilCreateView.as_view(), name="conta_contabil_create"),
    path("plano-de-contas/<int:pk>/editar/", ContaContabilUpdateView.as_view(), name="conta_contabil_update"),
    path("plano-de-contas/<int:pk>/excluir/", ContaContabilDeleteView.as_view(), name="conta_contabil_delete"),
    path("dre-contabil/", DREContabilView.as_view(), name="dre_contabil"),
    path("exportar/contabil/", ContabilExportView.as_view(), name="export_contabil"),
    path("novo/", TransactionCreateView.as_view(), name="create"),
    path("<int:pk>/editar/", TransactionUpdateView.as_view(), name="update"),
    path("<int:pk>/excluir/", TransactionDeleteView.as_view(), name="delete"),

    path("recorrentes/", RecurringPledgeListView.as_view(), name="recurring_pledges"),
    path("recorrentes/<int:pk>/alternar/", RecurringPledgeToggleView.as_view(), name="recurring_pledge_toggle"),
    path("recorrentes/<int:pk>/excluir/", RecurringPledgeDeleteView.as_view(), name="recurring_pledge_delete"),
    path("recorrentes/assinar/", RecurringPledgeSubscribeView.as_view(), name="recurring_pledge_subscribe"),
    path("recorrentes/<int:pk>/cancelar/", RecurringPledgeCancelView.as_view(), name="recurring_pledge_cancel"),
    path(
        "recorrentes/webhook/mercadopago/",
        RecurringPledgeMercadoPagoWebhookView.as_view(),
        name="recurring_pledge_webhook",
    ),

    path("doacoes/", DonationListView.as_view(), name="donation_list"),
    path("doacoes/nova/", DonationCreateView.as_view(), name="donation_create"),
    path("doacoes/<int:pk>/pagar/", DonationPayView.as_view(), name="donation_pay"),
    path("doacoes/<int:pk>/pagar/mercadopago/", DonationMercadoPagoStartView.as_view(), name="donation_mercadopago_start"),
    path("doacoes/<int:pk>/confirmar/", DonationConfirmPixView.as_view(), name="donation_confirm"),
    path("doacoes/<int:pk>/recibo.pdf", DonationReceiptPDFView.as_view(), name="donation_receipt"),
    path("doacoes/webhook/mercadopago/", DonationWebhookView.as_view(), name="donation_webhook"),

    path("recibo-anual.pdf", AnnualDonationReceiptPDFView.as_view(), name="annual_donation_receipt"),
    path("recibo-anual/<int:pk>.pdf", AnnualDonationReceiptPDFView.as_view(), name="annual_donation_receipt_for"),
]
