# Generated by Django 5.2.17 on 2026-08-24 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='people/photos/', verbose_name='Foto')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Solteiro(a)'), ('MARRIED', 'Casado(a)'), ('DIVORCED', 'Divorciado(a)'), ('WIDOWED', 'Viúvo(a)')], max_length=10, verbose_name='Estado civil')),
                ('phone', models.CharField(blank=True, help_text='Formato livre; normalizado para E.164 ao gerar o link do WhatsApp.', max_length=20, verbose_name='Telefone (WhatsApp)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('zip_code', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('is_visitor', models.BooleanField(default=False, verbose_name='É visitante')),
                ('is_member', models.BooleanField(default=False, verbose_name='É membro')),
                ('role', models.CharField(choices=[('VISITOR', 'Visitante'), ('MEMBER', 'Membro'), ('DEACON', 'Diácono'), ('DEACONESS', 'Diaconisa'), ('ELDER', 'Presbítero'), ('MUSICIAN', 'Músico'), ('DEPT_LEADER', 'Líder de Departamento'), ('PASTOR', 'Pastor')], default='VISITOR', max_length=15, verbose_name='Cargo')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Afastado'), ('VISITOR', 'Visitante')], default='VISITOR', max_length=10, verbose_name='Status')),
                ('member_since', models.DateField(blank=True, null=True, verbose_name='Membro desde')),
                ('baptized', models.BooleanField(default=False, verbose_name='Batizado')),
                ('baptism_date', models.DateField(blank=True, null=True, verbose_name='Data do batismo')),
                ('wants_membership', models.BooleanField(default=False, help_text='Marcado quando um visitante pede para se tornar membro pelo formulário público.', verbose_name='Solicitou membresia')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_created', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='people.department', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_departments', to='people.person', verbose_name='Líder'),
        ),
    ]
