# Generated by Django 5.2.17 on 2026-08-27 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da família')),
            ],
            options={
                'verbose_name': 'Família',
                'verbose_name_plural': 'Famílias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('color', models.CharField(default='#64748b', max_length=7, verbose_name='Cor')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='pipeline_stage',
            field=models.CharField(choices=[('NEW_VISITOR', 'Novo visitante'), ('FOLLOWING_UP', 'Em acompanhamento'), ('INTEGRATED', 'Integrado'), ('INACTIVE', 'Inativo no acompanhamento')], default='NEW_VISITOR', help_text='Pipeline de acompanhamento de visitantes (quadro em Pessoas → Acompanhamento).', max_length=15, verbose_name='Etapa de acompanhamento'),
        ),
        migrations.AddField(
            model_name='person',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='people.family', verbose_name='Família'),
        ),
        migrations.AddField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='people', to='people.tag', verbose_name='Tags'),
        ),
    ]
