# Generated by Django 5.2.17 on 2026-09-01 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_church_email_confirmed_alter_church_plano_and_more'),
        ('people', '0004_person_privacy_consent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='guardian',
            field=models.ForeignKey(blank=True, help_text='Quem busca essa pessoa — usado no check-in infantil pra saber quem pode retirar a criança. Diferente de `family` (agrupamento solto pra relatório): este campo é usado de verdade pelo check-in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependentes', to='people.person', verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='person',
            name='medical_notes',
            field=models.TextField(blank=True, help_text='Aparece em destaque na etiqueta impressa do check-in infantil — separado de `notes` de propósito, pra não se perder em observações gerais.', verbose_name='Restrições médicas/alergias'),
        ),
        migrations.AddField(
            model_name='person',
            name='pipeline_stage_changed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Etapa mudou em'),
        ),
        migrations.CreateModel(
            name='AutomacaoJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('NEW_VISITOR', 'Novo visitante'), ('FOLLOWING_UP', 'Em acompanhamento'), ('INTEGRATED', 'Integrado'), ('INACTIVE', 'Inativo no acompanhamento')], help_text='Regra dispara pra quem está NESSA etapa há `dias_depois` dias.', max_length=15, verbose_name='Etapa')),
                ('dias_depois', models.PositiveIntegerField(help_text='Quantos dias depois de entrar na etapa a mensagem é enviada.', verbose_name='Dias depois')),
                ('mensagem', models.TextField(help_text='Use {nome} pra personalizar — mesmo formato de MessageTemplate.', verbose_name='Mensagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
            ],
            options={
                'verbose_name': 'Automação de jornada',
                'verbose_name_plural': 'Automações de jornada',
                'ordering': ['etapa', 'dias_depois'],
            },
        ),
    ]
