# Generated by Django 5.2.17 on 2026-09-02 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_person_guardian_person_medical_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='habilita_checkin',
            field=models.BooleanField(default=False, help_text='Marque só pro departamento que atende o check-in infantil (ex.: Ministério Infantil/Kids) — libera essa tela pro líder dele.', verbose_name='Usa check-in infantil'),
        ),
        migrations.AlterField(
            model_name='department',
            name='leader',
            field=models.ForeignKey(blank=True, help_text='Quem lidera esse departamento — se essa pessoa tiver login com o cargo "Líder de Departamento", o acesso dela fica restrito aos recursos deste departamento (ver accounts.User.is_department_leader).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_departments', to='people.person', verbose_name='Líder'),
        ),
    ]
