# Generated by Django 5.2.17 on 2026-09-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_department_habilita_checkin_alter_department_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email_opted_out_at',
            field=models.DateTimeField(blank=True, help_text='Preenchido sozinho quando a pessoa clica "cancelar inscrição" num e-mail de campanha — a partir daí ela some do público de qualquer campanha nova (ver notifications.EmailMessage).', null=True, verbose_name='Descadastrado de e-mail em'),
        ),
    ]
