# Generated by Django 5.2.17 on 2026-09-03 20:38

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_person_email_opted_out_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.uploads._RandomUploadTo('people/photos'), verbose_name='Foto'),
        ),
    ]
