# Generated by Django 5.2.17 on 2026-08-24 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('meeting_weekday', models.IntegerField(blank=True, choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], null=True, verbose_name='Dia da semana')),
                ('meeting_time', models.TimeField(blank=True, null=True, verbose_name='Horário')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_cells', to='people.person', verbose_name='Líder')),
                ('members', models.ManyToManyField(blank=True, related_name='cells', to='people.person', verbose_name='Membros')),
            ],
            options={
                'verbose_name': 'Célula',
                'verbose_name_plural': 'Células',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CellMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('visitors_count', models.PositiveIntegerField(default=0, verbose_name='Visitantes (sem cadastro)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('attendees', models.ManyToManyField(blank=True, related_name='cell_meetings_attended', to='people.person', verbose_name='Presentes')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='cells.cell', verbose_name='Célula')),
            ],
            options={
                'verbose_name': 'Reunião',
                'verbose_name_plural': 'Reuniões',
                'ordering': ['-date'],
            },
        ),
    ]
