# Generated by Django 5.2.17 on 2026-09-01 21:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_church_email_confirmed_alter_church_plano_and_more'),
        ('people', '0005_person_guardian_person_medical_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaInfantil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('idade_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade mínima')),
                ('idade_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade máxima')),
                ('capacidade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidade')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
            ],
            options={
                'verbose_name': 'Sala infantil',
                'verbose_name_plural': 'Salas infantis',
                'ordering': ['idade_min', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=200, verbose_name='Nome da criança')),
                ('guardian_name', models.CharField(max_length=200, verbose_name='Nome do responsável')),
                ('guardian_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone do responsável')),
                ('pickup_code', models.CharField(blank=True, editable=False, max_length=4, verbose_name='Código de retirada')),
                ('checkin_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True, verbose_name='Check-in em')),
                ('checked_out_at', models.DateTimeField(blank=True, null=True, verbose_name='Check-out em')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_feitos', to=settings.AUTH_USER_MODEL, verbose_name='Check-in feito por')),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts_feitos', to=settings.AUTH_USER_MODEL, verbose_name='Check-out feito por')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='people.person', verbose_name='Criança')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='checkin.salainfantil', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
                'ordering': ['-checked_in_at'],
            },
        ),
    ]
