# Generated by Django 5.2.17 on 2026-09-03 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0022_church_ia_api_key_church_ia_chat_enabled_and_more'),
        ('notifications', '0012_whatsappinstance_disconnect_alert_sent'),
        ('people', '0007_person_email_opted_out_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Dígitos normalizados (mesmo formato de Person.whatsapp_number).', max_length=20, verbose_name='Telefone')),
                ('state', models.CharField(choices=[('MENU', 'Menu'), ('COLETANDO_CADASTRO', 'Coletando cadastro'), ('AGUARDANDO_CONFIRMACAO', 'Aguardando confirmação'), ('IA_LIVRE', 'Conversa livre com IA'), ('AGUARDANDO_HUMANO', 'Aguardando atendimento humano')], default='MENU', max_length=25, verbose_name='Estado')),
                ('state_data', models.JSONField(blank=True, default=dict, help_text='Progresso do wizard/dados extraídos em memória — nunca lido fora deste app.', verbose_name='Dados do estado')),
                ('last_message_at', models.DateTimeField(auto_now=True, verbose_name='Última mensagem em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
                ('instance', models.ForeignKey(blank=True, help_text='Por qual número (Evolution) essa conversa está rolando — em branco no canal Meta Cloud (só um número por igreja) ou enquanto a instância ainda não foi resolvida.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.whatsappinstance', verbose_name='Instância de WhatsApp')),
                ('person', models.ForeignKey(blank=True, help_text='Preenchida quando o telefone bate com um cadastro existente — só pra personalizar a saudação, nunca decide sozinha se um rascunho é criação ou atualização.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Recebida'), ('OUT', 'Enviada')], max_length=3, verbose_name='Direção')),
                ('body', models.TextField(verbose_name='Texto')),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Fragmento do webhook, só pra debug.', verbose_name='Payload cru')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Em')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='assistant.conversation', verbose_name='Conversa')),
            ],
            options={
                'verbose_name': 'Mensagem da conversa',
                'verbose_name_plural': 'Mensagens da conversa',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('WHATSAPP_IA', 'WhatsApp (assistente)'), ('PUBLIC_FORM', 'Formulário público')], max_length=15, verbose_name='Origem')),
                ('data', models.JSONField(help_text='Só chaves da allow-list (PERSON_DRAFT_ALLOWED_FIELDS) — nunca cargo/status/departamento/etc.', verbose_name='Dados propostos')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='PENDING', max_length=10, verbose_name='Status')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Solicitado em')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo da rejeição')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistant.conversation', verbose_name='Conversa de origem')),
                ('person', models.ForeignKey(blank=True, help_text='Em branco = cadastro novo (visitante); preenchida = atualização de quem já existe.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='people.person', verbose_name='Pessoa')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Processado por')),
            ],
            options={
                'verbose_name': 'Cadastro pendente',
                'verbose_name_plural': 'Cadastros pendentes',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonUpdateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Último uso em')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_links', to='people.person', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Link de atualização cadastral',
                'verbose_name_plural': 'Links de atualização cadastral',
            },
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('church', 'phone'), name='unique_conversation_per_phone'),
        ),
    ]
