# Generated by Django 5.2.17 on 2026-08-24 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='links', unique=True, verbose_name='Slug')),
                ('church_name', models.CharField(max_length=150, verbose_name='Nome da igreja')),
                ('headline', models.CharField(blank=True, max_length=200, verbose_name='Frase de destaque')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='linkbio/avatars/', verbose_name='Foto/logo')),
                ('background_color', models.CharField(default='#0f172a', max_length=7, verbose_name='Cor de fundo')),
                ('accent_color', models.CharField(default='#38bdf8', max_length=7, verbose_name='Cor de destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Página de links',
                'verbose_name_plural': 'Páginas de links',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('url', models.URLField(verbose_name='URL')),
                ('link_type', models.CharField(choices=[('SOCIAL', 'Rede social'), ('LIVE', 'Culto ao vivo'), ('DONATION', 'Doação'), ('EVENT', 'Evento'), ('OTHER', 'Outro')], default='OTHER', max_length=10, verbose_name='Tipo')),
                ('icon', models.CharField(blank=True, help_text="Nome do ícone (ex.: 'instagram', 'youtube') usado no template.", max_length=50, verbose_name='Ícone')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('click_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Cliques')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='linkbio.biopage', verbose_name='Página')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ['order', 'id'],
            },
        ),
    ]
