# Generated by Django 5.2.17 on 2026-09-03 20:38

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkbio', '0002_church_scoping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biopage',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.uploads._RandomUploadTo('linkbio/avatars'), verbose_name='Foto/logo'),
        ),
    ]
