# Generated by Django 5.2.17 on 2026-08-28 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_family_tag_person_pipeline_stage_person_family_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, help_text='Desligue para fechar o formulário sem apagar as respostas já recebidas.', verbose_name='Aceitando respostas')),
                ('send_whatsapp_confirmation', models.BooleanField(default=False, help_text='Opcional — exige um campo marcado como "telefone" abaixo, em Campos.', verbose_name='Disparar mensagem de WhatsApp ao responder')),
                ('whatsapp_message_template', models.TextField(blank=True, default='Obrigado {nome}! Recebemos sua resposta para "{formulario}".', help_text='Use {nome} (campo marcado como nome) e {formulario} (título deste formulário).', verbose_name='Mensagem de confirmação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_forms_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Formulário',
                'verbose_name_plural': 'Formulários',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Pergunta')),
                ('field_type', models.CharField(choices=[('TEXT', 'Texto curto'), ('TEXTAREA', 'Texto longo'), ('EMAIL', 'E-mail'), ('PHONE', 'Telefone'), ('NUMBER', 'Número'), ('DATE', 'Data'), ('CHOICE', 'Escolha única'), ('MULTIPLE_CHOICE', 'Múltipla escolha')], default='TEXT', max_length=20, verbose_name='Tipo')),
                ('options', models.TextField(blank=True, help_text='Uma por linha — só usado em "Escolha única"/"Múltipla escolha".', verbose_name='Opções')),
                ('required', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_name_field', models.BooleanField(default=False, help_text='Marque em só um campo — geralmente o do nome completo.', verbose_name='Usar como {nome} na mensagem de confirmação')),
                ('is_phone_field', models.BooleanField(default=False, help_text='Precisa estar marcado em um campo para o disparo de WhatsApp funcionar.', verbose_name='Usar como telefone (WhatsApp) para o disparo')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='custom_forms.customform', verbose_name='Formulário')),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='custom_forms.customform', verbose_name='Formulário')),
                ('person', models.ForeignKey(blank=True, help_text='Preenchido automaticamente quando quem responde está logado e tem cadastro vinculado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_responses', to='people.person', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, verbose_name='Valor')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='custom_forms.formfield', verbose_name='Campo')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='custom_forms.formresponse', verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Resposta de campo',
                'verbose_name_plural': 'Respostas de campo',
            },
        ),
    ]
