# Generated by Django 5.2.17 on 2026-08-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formanswer',
            name='file',
            field=models.FileField(blank=True, help_text='Só preenchido quando o campo é do tipo "Arquivo (anexo)".', null=True, upload_to='custom_forms/respostas/%Y/%m/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'Texto curto'), ('TEXTAREA', 'Texto longo'), ('NAME', 'Nome completo'), ('EMAIL', 'E-mail'), ('PHONE', 'Telefone/WhatsApp'), ('CPF', 'CPF'), ('BIRTH_DATE', 'Data de nascimento'), ('ADDRESS', 'Endereço'), ('CITY', 'Cidade'), ('STATE', 'Estado (UF)'), ('ZIP_CODE', 'CEP'), ('GENDER', 'Sexo'), ('MARITAL_STATUS', 'Estado civil'), ('DATE', 'Data'), ('TIME', 'Horário'), ('NUMBER', 'Número'), ('URL', 'Link (URL)'), ('YES_NO', 'Sim/Não'), ('FILE', 'Arquivo (anexo)'), ('CHOICE', 'Escolha única (opções personalizadas)'), ('MULTIPLE_CHOICE', 'Múltipla escolha (opções personalizadas)')], default='TEXT', max_length=20, verbose_name='Tipo'),
        ),
    ]
