# Generated by Django 5.2.17 on 2026-08-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_forms', '0002_formanswer_file_alter_formfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customform',
            name='notify_staff_emails',
            field=models.CharField(blank=True, help_text='Opcional — um ou mais e-mails separados por vírgula. Deixe em branco pra não avisar ninguém.', max_length=500, verbose_name='Avisar por e-mail quando chegar resposta'),
        ),
        migrations.AddField(
            model_name='customform',
            name='sync_to_person',
            field=models.BooleanField(default=False, help_text='Opcional — usa os campos do tipo Nome, Telefone, E-mail, Data de nascimento etc. pra achar (por telefone, ou pelo login de quem respondeu) ou criar a pessoa no cadastro.', verbose_name='Criar/atualizar cadastro de pessoa automaticamente'),
        ),
    ]
