# Generated by Django 5.2.17 on 2026-08-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_forms', '0004_church_scoping'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='privacy_consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consentimento LGPD em'),
        ),
    ]
