# Generated by Django 5.2.17 on 2026-09-03 20:38

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_forms', '0005_formresponse_privacy_consent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formanswer',
            name='file',
            field=models.FileField(blank=True, help_text='Só preenchido quando o campo é do tipo "Arquivo (anexo)".', null=True, upload_to=core.uploads._RandomUploadTo('custom_forms/respostas'), verbose_name='Arquivo'),
        ),
    ]
