# Generated by Django 5.2.17 on 2026-08-25 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Snapshot do número no momento do envio — funciona mesmo se não vinculado a uma Pessoa.', max_length=20, verbose_name='Telefone')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando'), ('SENT', 'Enviada'), ('FAILED', 'Falhou'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=10, verbose_name='Status')),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Em branco = envia assim que a fila for processada.', null=True, verbose_name='Agendada para')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada em')),
                ('error_message', models.CharField(blank=True, max_length=255, verbose_name='Erro')),
                ('campaign_label', models.CharField(blank=True, help_text="Rótulo livre pra agrupar um envio em massa (ex.: 'Culto especial 24/08').", max_length=100, verbose_name='Campanha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages_created', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='people.person', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Mensagem de WhatsApp',
                'verbose_name_plural': 'Mensagens de WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
