# Generated by Django 5.2.17 on 2026-08-25 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entregue em'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='delivery_status',
            field=models.CharField(choices=[('UNKNOWN', 'Desconhecido'), ('DELIVERED', 'Entregue'), ('READ', 'Lida'), ('FAILED', 'Falha na entrega')], default='UNKNOWN', max_length=10, verbose_name='Status de entrega'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='external_id',
            field=models.CharField(blank=True, help_text='Devolvido pela API no envio — usado pra casar com o evento de confirmação do webhook.', max_length=100, verbose_name='ID na Evolution API'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lida em'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Quantas vezes já tentou enviar — o processador da fila para de tentar de novo sozinho depois de ChurchConfig.whatsapp_max_retries.', verbose_name='Tentativas'),
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('body', models.TextField(help_text='Pode usar {nome} — substituído pelo nome do destinatário no envio.', verbose_name='Texto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Modelo de mensagem',
                'verbose_name_plural': 'Modelos de mensagem',
                'ordering': ['name'],
            },
        ),
    ]
