# Generated by Django 5.2.17 on 2026-09-02 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_church_api_key_church_email_batch_size_church_matriz'),
        ('notifications', '0004_church_scoping'),
        ('people', '0006_department_habilita_checkin_alter_department_leader'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Snapshot no momento do envio.', max_length=254, verbose_name='E-mail')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto')),
                ('body', models.TextField(help_text='Texto simples — envolvido num modelo visual simples no envio.', verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando'), ('SENT', 'Enviada'), ('FAILED', 'Falhou'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=10, verbose_name='Status')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Agendada para')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada em')),
                ('error_message', models.CharField(blank=True, max_length=255, verbose_name='Erro')),
                ('campaign_label', models.CharField(blank=True, max_length=100, verbose_name='Campanha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_messages_created', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_messages', to='people.person', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'E-mail em massa',
                'verbose_name_plural': 'E-mails em massa',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Snapshot no momento do envio.', max_length=20, verbose_name='Telefone')),
                ('message', models.CharField(max_length=320, verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando'), ('SENT', 'Enviada'), ('FAILED', 'Falhou'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=10, verbose_name='Status')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Agendada para')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada em')),
                ('error_message', models.CharField(blank=True, max_length=255, verbose_name='Erro')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Tentativas')),
                ('campaign_label', models.CharField(blank=True, max_length=100, verbose_name='Campanha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages_created', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='people.person', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'SMS',
                'verbose_name_plural': 'SMS',
                'ordering': ['-created_at'],
            },
        ),
    ]
