# Generated by Django 5.2.17 on 2026-09-02 17:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_emailmessage_smsmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Cliques'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Clicado em'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='open_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Vezes aberto'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aberto em'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='tracking_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
