# Generated by Django 5.2.17 on 2026-09-03 01:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_church_whatsapp_meta_business_account_id'),
        ('notifications', '0006_emailmessage_click_count_emailmessage_clicked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMetaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Identifica o template na Meta — não pode ser alterado depois de criado.', max_length=512, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+$', 'Use só letras minúsculas, números e _ (exigência da Meta).')], verbose_name='Nome')),
                ('language', models.CharField(default='pt_BR', max_length=10, verbose_name='Idioma')),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('utility', 'Utilidade'), ('authentication', 'Autenticação')], default='utility', max_length=20, verbose_name='Categoria')),
                ('header_text', models.CharField(blank=True, help_text='Texto simples, sem variável — só a versão de texto do cabeçalho é suportada aqui.', max_length=60, verbose_name='Cabeçalho (opcional)')),
                ('body_text', models.TextField(help_text='Use {{1}}, {{2}}... para variáveis — sintaxe posicional da própria Meta, diferente do {nome} usado nos templates locais de WhatsApp/e-mail.', verbose_name='Corpo da mensagem')),
                ('footer_text', models.CharField(blank=True, max_length=60, verbose_name='Rodapé (opcional)')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PENDING', 'Em análise pela Meta'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('DISABLED', 'Desativado')], default='DRAFT', max_length=10, verbose_name='Status')),
                ('meta_template_id', models.CharField(blank=True, help_text='Preenchido só depois de enviado pra aprovação — usado pra consultar status/excluir.', max_length=100, verbose_name='ID na Meta')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo da rejeição')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado pra aprovação em')),
                ('status_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Status atualizado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
            ],
            options={
                'verbose_name': 'Template Meta (WhatsApp)',
                'verbose_name_plural': 'Templates Meta (WhatsApp)',
                'ordering': ['-created_at'],
            },
        ),
    ]
