# Generated by Django 5.2.17 on 2026-09-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_whatsappmetatemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmetatemplate',
            name='buttons',
            field=models.JSONField(blank=True, default=list, help_text='Até 3 botões — TODOS de resposta rápida OU até 2 de link/telefone, nunca misturados (regra da própria Meta). Montado pelo formulário, não digitado direto.', verbose_name='Botões'),
        ),
    ]
