# Generated by Django 5.2.17 on 2026-09-03 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_whatsappmetatemplate_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='meta_template',
            field=models.ForeignKey(blank=True, help_text='Preenchido só quando o envio deve tentar usar um template aprovado da API oficial da Meta — fora da janela de 24h, é a única forma de mandar mensagem por lá. Se o template não estiver mais aprovado na hora do envio, cai pro texto livre acima.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_enviadas', to='notifications.whatsappmetatemplate', verbose_name='Template Meta (opcional)'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='meta_template_values',
            field=models.JSONField(blank=True, default=list, help_text='Lista na ordem {{1}}, {{2}}... já resolvida (ex.: {nome} já virou o nome de verdade).', verbose_name='Valores das variáveis do template'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='message',
            field=models.TextField(help_text='Texto já renderizado e legível — sempre preenchido, mesmo quando enviada via template Meta abaixo (serve de fallback pro canal Evolution, pro e-mail de fallback e pro log/auditoria).', verbose_name='Mensagem'),
        ),
    ]
