# Generated by Django 5.2.17 on 2026-09-03 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_church_whatsapp_max_instancias_and_more'),
        ('notifications', '0009_whatsappmessage_meta_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='WhatsApp da igreja', help_text='Só pra identificar esse número nas telas (ex.: "WhatsApp da igreja", "WhatsApp do pastor").', max_length=100, verbose_name='Nome')),
                ('whatsapp_instance', models.CharField(blank=True, help_text='Nome real no servidor Evolution (compartilhado por todas as igrejas) — gerado sozinho.', max_length=100, unique=True, verbose_name='Nome da instância')),
                ('whatsapp_instance_token', models.CharField(blank=True, help_text='Preenchida automaticamente ao criar a instância pelo admin.', max_length=200, verbose_name='Chave da instância')),
                ('webhook_secret', models.CharField(blank=True, help_text='Conferido no cabeçalho X-Webhook-Secret pra confirmar de qual instância é o evento de confirmação de entrega — gerado sozinho.', max_length=100, verbose_name='Segredo do webhook')),
                ('send_interval_seconds', models.PositiveIntegerField(default=6, help_text='Espera entre uma mensagem e outra desta instância — mandar tudo de uma vez é o jeito mais rápido do WhatsApp marcar o número como spam. 5-10s é um valor seguro.', verbose_name='Intervalo entre envios (segundos)')),
                ('batch_size', models.PositiveIntegerField(default=30, help_text='Limite de mensagens desta instância enviadas numa única chamada do comando processar_fila_whatsapp — o resto fica pra próxima execução do cron.', verbose_name='Mensagens por execução da fila')),
                ('max_retries', models.PositiveIntegerField(default=3, help_text='Quantas vezes o processador da fila tenta reenviar uma mensagem desta instância que falhou antes de parar de tentar sozinho.', verbose_name='Tentativas antes de desistir')),
                ('is_default', models.BooleanField(default=False, help_text='Usada por avisos automáticos (escala, lembrete, jornada...) que não perguntam qual número usar — só uma instância por igreja pode ser a padrão.', verbose_name='Instância padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Igreja')),
            ],
            options={
                'verbose_name': 'Instância de WhatsApp',
                'verbose_name_plural': 'Instâncias de WhatsApp',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='instance',
            field=models.ForeignKey(blank=True, help_text='Por qual número (Evolution API) esta mensagem sai — só faz sentido pra igrejas com mais de uma instância conectada; em branco, o processador da fila usa a instância padrão da igreja. Ignorado no canal oficial da Meta (só tem um número por igreja).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens', to='notifications.whatsappinstance', verbose_name='Instância de WhatsApp'),
        ),
    ]
