# Generated by Django 5.2.17 on 2026-09-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_migrar_instancia_evolution_da_church'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappinstance',
            name='disconnect_alert_sent',
            field=models.BooleanField(default=False, help_text='Controle interno de verificar_conexao_whatsapp — evita mandar e-mail novo a cada execução do cron enquanto a mesma queda continua; zera sozinho quando reconectar.', verbose_name='Já avisou sobre desconexão atual'),
        ),
    ]
